<?php
declare(strict_types=1);

// MathFunctionParser SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MathFunctionParserUtility::setRegistrar(function (MathFunctionParserUtility $u): void {
    $u->clean = [MathFunctionParserClean::class, 'call'];
    $u->done = [MathFunctionParserDone::class, 'call'];
    $u->make_error = [MathFunctionParserMakeError::class, 'call'];
    $u->feature_add = [MathFunctionParserFeatureAdd::class, 'call'];
    $u->feature_hook = [MathFunctionParserFeatureHook::class, 'call'];
    $u->feature_init = [MathFunctionParserFeatureInit::class, 'call'];
    $u->fetcher = [MathFunctionParserFetcher::class, 'call'];
    $u->make_fetch_def = [MathFunctionParserMakeFetchDef::class, 'call'];
    $u->make_context = [MathFunctionParserMakeContext::class, 'call'];
    $u->make_options = [MathFunctionParserMakeOptions::class, 'call'];
    $u->make_request = [MathFunctionParserMakeRequest::class, 'call'];
    $u->make_response = [MathFunctionParserMakeResponse::class, 'call'];
    $u->make_result = [MathFunctionParserMakeResult::class, 'call'];
    $u->make_point = [MathFunctionParserMakePoint::class, 'call'];
    $u->make_spec = [MathFunctionParserMakeSpec::class, 'call'];
    $u->make_url = [MathFunctionParserMakeUrl::class, 'call'];
    $u->param = [MathFunctionParserParam::class, 'call'];
    $u->prepare_auth = [MathFunctionParserPrepareAuth::class, 'call'];
    $u->prepare_body = [MathFunctionParserPrepareBody::class, 'call'];
    $u->prepare_headers = [MathFunctionParserPrepareHeaders::class, 'call'];
    $u->prepare_method = [MathFunctionParserPrepareMethod::class, 'call'];
    $u->prepare_params = [MathFunctionParserPrepareParams::class, 'call'];
    $u->prepare_path = [MathFunctionParserPreparePath::class, 'call'];
    $u->prepare_query = [MathFunctionParserPrepareQuery::class, 'call'];
    $u->graphql_body = [MathFunctionParserGraphql::class, 'body'];
    $u->graphql_errors = [MathFunctionParserGraphql::class, 'errors'];
    $u->result_basic = [MathFunctionParserResultBasic::class, 'call'];
    $u->result_body = [MathFunctionParserResultBody::class, 'call'];
    $u->result_headers = [MathFunctionParserResultHeaders::class, 'call'];
    $u->transform_request = [MathFunctionParserTransformRequest::class, 'call'];
    $u->transform_response = [MathFunctionParserTransformResponse::class, 'call'];
});
